const assert = require('node:assert/strict');
const {due,progress,cookieDomain,subscriptionAnchor} = require('../app/static/blog/assets/reader-subscription.js');
assert.equal(due(null,0),true);
assert.equal(due(1000,1000+86400000-1),false);
assert.equal(due(1000,1000+86400000),true);
assert.equal(due(NaN,100000000),false);
assert.equal(due(100000001,100000000),false);
assert.equal(progress(100,1100,600,[]),.5);
assert.equal(progress(100,1100,700,[{top:500,height:200}]),.5);
assert.equal(progress(100,1100,1100,[{top:900,height:200}]),1);
assert.equal(progress(100,100,100,[]),0);
assert.equal(cookieDomain('blog.edabalans.ru'),'edabalans.ru');
assert.equal(cookieDomain('go.xn-----jlceacr3bggd8ajed5a6kl.xn--p1ai'),'xn-----jlceacr3bggd8ajed5a6kl.xn--p1ai');
assert.equal(cookieDomain('edabalans.ru.evil.test'),undefined);
assert.equal(cookieDomain('notedabalans.ru'),undefined);
const first = {id:'first'}, next = {id:'first-next'}, selected = {id:'selected'};
const article = id => ({dataset:{subscriptionBeforeHeading:id},querySelectorAll(selector){
  assert.equal(selector,':scope > h2');
  return [first,next,selected];
}});
assert.equal(subscriptionAnchor(article('selected')),selected);
assert.equal(subscriptionAnchor(article('first')),first);
assert.equal(subscriptionAnchor(article('missing')),undefined);
assert.equal(subscriptionAnchor(article('fir')),undefined,'A prefix must not relocate the insertion');
assert.equal(subscriptionAnchor(article(undefined)),undefined);
console.log('reader subscription timing, domain, progress and curated anchor assertions passed');
