from tools.build_intensive_bot_content import OUTPUT, compiled_items, markdown_to_telegram_html, render_module


def test_markdown_to_telegram_html_supports_owner_formatting():
    rendered = markdown_to_telegram_html(
        "**Жирно** и *курсив*, [ссылка]({{personal_intensive_url}}), ||спойлер||\n\n> цитата"
    )

    assert rendered == (
        '<b>Жирно</b> и <i>курсив</i>, '
        '<a href="{{personal_intensive_url}}">ссылка</a>, '
        '<tg-spoiler>спойлер</tg-spoiler>\n\n<blockquote>цитата</blockquote>'
    )


def test_compiler_keeps_md_as_source_and_preserves_direct_channel_links():
    items = compiled_items()

    assert "intensive_mid1_unsubscribed" in items
    assert "https://t.me/Fitness_Talks/698" in items["intensive_mid1_unsubscribed"]
    assert "{{personal_channel_post_" not in items["intensive_mid1_unsubscribed"]
    assert render_module(items).startswith('"""Generated by tools/build_intensive_bot_content.py')


def test_generated_runtime_module_is_in_sync():
    assert OUTPUT.read_text(encoding="utf-8") == render_module(compiled_items())
