"""Compile owner-approved intensive Markdown into the Telegram runtime seed.

The files in work/free-intensive-rebuild/bot-messages remain the editable source.
The generated Python module is a deployable derivative and must not be edited by
hand.
"""

from __future__ import annotations

import html
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "work" / "free-intensive-rebuild" / "bot-messages"
OUTPUT = ROOT / "telegram-bot" / "service" / "app" / "generated_intensive_content.py"

SOURCES = {
    "intensive_entry_default": "intensive-entry-default.md",
    "intensive_entry_yandex": "intensive-entry-yandex.md",
    "intensive_entry_continue": "intensive-entry-continue.md",
    "intensive_entry_delivered": "intensive-entry-delivered.md",
    "intensive_entry_legacy_update": "intensive-entry-legacy-update.md",
    "start_masterclass_owned": "start-masterclass-owned.md",
    "intensive_day1_reminder": "intensive-day1-reminder.md",
    "intensive_day2": "intensive-day2.md",
    "intensive_day3": "intensive-day3.md",
    "intensive_day4": "intensive-day4.md",
    "intensive_mid1_subscribed": "intensive-mid1-subscribed.md",
    "intensive_mid1_unsubscribed": "intensive-mid1-unsubscribed.md",
    "intensive_mid2_subscribed": "intensive-mid2-subscribed.md",
    "intensive_mid2_unsubscribed": "intensive-mid2-unsubscribed.md",
    "intensive_mid3_subscribed": "intensive-mid3-subscribed.md",
    "intensive_mid3_unsubscribed": "intensive-mid3-unsubscribed.md",
    "intensive_masterclass_pin": "intensive-masterclass-pin.md",
    "max_forwarded_assignment_day1": "max-forwarded-assignment-day1.md",
    "max_forwarded_assignment_day2": "max-forwarded-assignment-day2.md",
    "max_forwarded_assignment_day3": "max-forwarded-assignment-day3.md",
}

VARIABLE_ALIASES = {
    "PERSONAL_INTENSIVE_URL": "personal_intensive_url",
    "PERSONAL_MASTERCLASS_URL": "personal_masterclass_url",
}
LITERAL_REPLACEMENTS = {
    "{{personal_max_url}}": "https://max.ru/u/f9LHodD0cOJjmbADdxMaO0UzEfR_55NRvOSwSuS3C6mWE5T27DPcpczbvEw",
}
MAX_ASSIGNMENT_TEXT_LIMIT = 4000


def source_body(path: Path) -> str:
    value = path.read_text(encoding="utf-8")
    if not value.startswith("---\n"):
        raise ValueError(f"missing front matter: {path}")
    _, _, remainder = value.partition("\n---\n")
    if not remainder:
        raise ValueError(f"unterminated front matter: {path}")
    return remainder.strip()


def markdown_to_telegram_html(value: str) -> str:
    value = value.replace(r"\[", "[").replace(r"\]", "]")
    value = html.escape(value, quote=False)
    value = re.sub(
        r"\[([^\]]+)]\((https?://[^\s)]+|\{\{[a-zA-Z0-9_]+}})\)",
        r'<a href="\2">\1</a>',
        value,
    )
    value = re.sub(r"\*\*([^*\n]+)\*\*", r"<b>\1</b>", value)
    value = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<i>\1</i>", value)
    value = re.sub(r"\|\|([^|\n]+)\|\|", r"<tg-spoiler>\1</tg-spoiler>", value)
    lines: list[str] = []
    for line in value.splitlines():
        if line.startswith("&gt; "):
            line = f"<blockquote>{line[5:]}</blockquote>"
        lines.append(line)
    return "\n".join(lines).strip()


def compiled_items() -> dict[str, str]:
    result: dict[str, str] = {}
    for content_id, filename in SOURCES.items():
        body = source_body(SOURCE / filename)
        for old, new in VARIABLE_ALIASES.items():
            body = body.replace("{{" + old + "}}", "{{" + new + "}}")
        for old, new in LITERAL_REPLACEMENTS.items():
            body = body.replace(old, new)
        rendered = markdown_to_telegram_html(body)
        if content_id.startswith("max_forwarded_assignment_") and len(rendered) > MAX_ASSIGNMENT_TEXT_LIMIT:
            raise ValueError(
                f"MAX assignment exceeds {MAX_ASSIGNMENT_TEXT_LIMIT} characters: "
                f"{content_id} ({len(rendered)})"
            )
        result[content_id] = rendered
    return result


def render_module(items: dict[str, str]) -> str:
    lines = [
        '"""Generated by tools/build_intensive_bot_content.py; do not edit."""',
        "",
        "APPROVED_INTENSIVE_CONTENT = {",
    ]
    for code, body in items.items():
        lines.append(f"    {code!r}: {body!r},")
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render_module(compiled_items()), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
